# Generated by Django 3.0.4 on 2020-04-05 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_objects',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientcategoryconnection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='recipes.IngredientCategory'),
        ),
        migrations.AddField(
            model_name='ingredientcategoryconnection',
            name='base_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_connections', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='ingredients',
            field=models.ManyToManyField(related_name='categories', through='recipes.IngredientCategoryConnection', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='recipes.IngredientCategory'),
        ),
        migrations.AddField(
            model_name='variation',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='variations', to='recipes.Recipe'),
        ),
    ]
