# Generated by Django 3.1.2 on 2020-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='origin_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('g', 'grams'), ('kg', 'kilograms'), ('dl', 'deciliters'), ('cl', 'centiliters'), ('ml', 'milliliters'), ('L', 'liters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('', 'count'), ('slices', 'slices')], default='', max_length=16),
        ),
    ]
