# Generated by Django 3.0.4 on 2020-04-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200404_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name_plural': 'Ingredient categories'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name_plural': 'Recipe categories'},
        ),
    ]
