# Generated by Django 3.0.4 on 2020-04-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200405_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('g', 'grams'), ('L', 'liters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('', '')], default='', max_length=5),
        ),
    ]
