# Generated by Django 3.0.4 on 2020-04-06 21:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200405_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('g', 'grams'), ('L', 'liters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('', 'count')], default='', max_length=5),
        ),
    ]
