# Generated by Django 3.0.4 on 2020-04-07 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200406_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='missing-slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
