# Generated by Django 3.0.4 on 2020-04-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200407_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount_per_serving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('g', 'grams'), ('dl', 'deciliters'), ('L', 'liters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('', 'count')], default='', max_length=5),
        ),
    ]
