# Generated by Django 3.0.4 on 2020-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200407_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('g', 'grams'), ('kg', 'kilograms'), ('dl', 'deciliters'), ('L', 'liters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('', 'count')], default='', max_length=5),
        ),
    ]
