# Generated by Django 3.0.4 on 2020-04-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200407_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientcategoryconnection',
            old_name='base_ingredient',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_objects',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='base_ingredient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usages', to='recipes.Ingredient'),
        ),
    ]
