# Generated by Django 3.0.4 on 2020-04-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200409_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='base_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usages', to='recipes.Ingredient'),
        ),
    ]
